### ISSUE TITLE
Launcher startup failure on Windows -- TTS-related

### ISSUE THREAD

**Issue by matatk** [matatk/agrip#17]
Christoff Eilers discovered a problem on Windows XP whereby the launcher could not start; the log is as follows.

```
Z:\Windows_XP_shared\aqlauncher\AudioQuake.app\Contents\MacOS>python AudioQuake.
py
send LIC_CLIENT_CONNECT
Traceback (most recent call last):
  File "AudioQuake.py", line 207, in <module>
    launcher = LauncherSingletonWindow(app)
  File "AudioQuake.py", line 141, in __init__
    self._game_controller = GameController()
  File "AudioQuake.py", line 68, in __init__
    self._speaker = pyttsx.init()
  File "Z:\Windows_XP_shared\aqlauncher\AudioQuake.app\Contents\MacOS\pyttsx\__i
nit__.py", line 39, in init
    eng = Engine(driverName, debug)
  File "Z:\Windows_XP_shared\aqlauncher\AudioQuake.app\Contents\MacOS\pyttsx\eng
ine.py", line 45, in __init__
    self.proxy = driver.DriverProxy(weakref.proxy(self), driverName, debug)
  File "Z:\Windows_XP_shared\aqlauncher\AudioQuake.app\Contents\MacOS\pyttsx\dri
ver.py", line 66, in __init__
    self._driver = self._module.buildDriver(weakref.proxy(self))
  File "Z:\Windows_XP_shared\aqlauncher\AudioQuake.app\Contents\MacOS\pyttsx\dri
vers\sapi5.py", line 37, in buildDriver
    return SAPI5Driver(proxy)
  File "Z:\Windows_XP_shared\aqlauncher\AudioQuake.app\Contents\MacOS\pyttsx\dri
vers\sapi5.py", line 56, in __init__
    self.setProperty('voice', self.getProperty('voice'))
  File "Z:\Windows_XP_shared\aqlauncher\AudioQuake.app\Contents\MacOS\pyttsx\dri
vers\sapi5.py", line 87, in getProperty
    return self._tts.Voice.Id
  File "C:\Python27\lib\site-packages\win32com\client\dynamic.py", line 511, in
__getattr__
    ret = self._oleobj_.Invoke(retEntry.dispid,0,invoke_type,1)
pywintypes.com_error: (-2147352567, "Une exception s'est produite.", (0, None, N
one, None, 0, -2147200966), None)
```

**Comment by matatk** [comment]
Quite a lot of time has passed (sorry about that!) so I am going to close this for now. Things are working well (for me, at least) on Windows 10. Unfortunately I can't check things out on earlier versions of Windows any more.
