### ISSUE TITLE
Launcher Error on Vista

### ISSUE THREAD

**Issue by matatk** [matatk/agrip#25]
Traceback (most recent call last):  File "C:\Python27\lib\site-packages\cx_Freeze\initscripts\Console.py", line 27, in <module>  File "AudioQuake.py", line 7, in <module>  File "C:\Python27\lib\site-packages\GUI__init__.py", line 74, in <module>  File "C:\Python27\lib\site-packages\GUI\Colors.py", line 8, in <module>  File "C:\Python27\lib\site-packages\GUI\Color.py", line 8, in <module>ImportError: DLL load failed: Nie można uruchomić aplikacji, ponieważ jej konfiguracja równoczesna jest niewłaściwa. Więcej szczegółów można znaleźć w dzienniku zdarzeń aplikacji.

[original report](http://forum.audiogames.net/viewtopic.php?pid=191953#p191953)

**Comment by matatk** [comment]
Quite a lot of time has passed (sorry about that!) so I am going to close this for now. Things are working well (for me, at least) on Windows 10. Unfortunately I can't check things out on earlier versions of Windows any more.
